/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DistributionRouteImport } from './routes/distribution'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as SupplyRouteImport } from './routes/supply'
import { Route as AdminTargetsRouteImport } from './routes/admin.targets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionRoute = DistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyRoute = SupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTargetsRoute = AdminTargetsRouteImport.update({
  id: '/admin/targets',
  path: '/admin/targets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/distribution': typeof DistributionRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
  '/supply': typeof SupplyRoute
  '/admin/targets': typeof AdminTargetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/distribution': typeof DistributionRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
  '/supply': typeof SupplyRoute
  '/admin/targets': typeof AdminTargetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/distribution': typeof DistributionRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
  '/supply': typeof SupplyRoute
  '/admin/targets': typeof AdminTargetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/distribution'
    | '/login'
    | '/production'
    | '/quality'
    | '/supply'
    | '/admin/targets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/distribution'
    | '/login'
    | '/production'
    | '/quality'
    | '/supply'
    | '/admin/targets'
  id:
    | '__root__'
    | '/'
    | '/distribution'
    | '/login'
    | '/production'
    | '/quality'
    | '/supply'
    | '/admin/targets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistributionRoute: typeof DistributionRoute
  LoginRoute: typeof LoginRoute
  ProductionRoute: typeof ProductionRoute
  QualityRoute: typeof QualityRoute
  SupplyRoute: typeof SupplyRoute
  AdminTargetsRoute: typeof AdminTargetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution': {
      id: '/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof DistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply': {
      id: '/supply'
      path: '/supply'
      fullPath: '/supply'
      preLoaderRoute: typeof SupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/targets': {
      id: '/admin/targets'
      path: '/admin/targets'
      fullPath: '/admin/targets'
      preLoaderRoute: typeof AdminTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistributionRoute: DistributionRoute,
  LoginRoute: LoginRoute,
  ProductionRoute: ProductionRoute,
  QualityRoute: QualityRoute,
  SupplyRoute: SupplyRoute,
  AdminTargetsRoute: AdminTargetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
